### ISSUE TITLE
help

### ISSUE THREAD

**Issue by enea1982** [alefiori82/amazon-paapi5#15]
guys to me from this mistake can you help me?

Status code: 401
Errors : {"__type":"com.amazon.paapi5#InvalidSignatureException","Errors":[{"Code":"InvalidSignature","Message":"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.com/paapi5/documentation/sending-request.html#signing."}]}
Request ID:
INFO:root:'NoneType' object is not iterable
Error calling PA-API 5.0!
Status code: 401
Errors : {"__type":"com.amazon.paapi5#InvalidSignatureException","Errors":[{"Code":"InvalidSignature","Message":"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.com/paapi5/documentation/sending-request.html#signing."}]}
Request ID:b
INFO:root:'NoneType' object is not iterable

**Comment by alefiori82** [comment]
Enter the values of KEY, SECRET, TAG and COUNTRY correctly. Otherwise, the request cannot be processed by Amazon.
The account must be enabled for Amazon API. This occurs after 3 confirmed purchases with your account.
Verify that all these information are entered correctly in the code.

**Comment by enea1982** [comment]
the tag what is username then there is another error this  

Traceback (most recent call last):
  File "/home/demian82/Desktop/AmazonOffers-TelegramBot-main/bot.py", line 4, in <module>
    from amazon_api import search_items
  File "/home/demian82/Desktop/AmazonOffers-TelegramBot-main/amazon_api.py", line 2, in <module>
    from paapi5_python_sdk.models.partner_type import PartnerType
ModuleNotFoundError: No module named 'paapi5_python_sdk.models'

**Comment by enea1982** [comment]
> Enter the values of KEY, SECRET, TAG and COUNTRY correctly. Otherwise, the request cannot be processed by Amazon. The account must be enabled for Amazon API. This occurs after 3 confirmed purchases with your account. Verify that all these information are entered correctly in the code.

if you can please help me install it thanks

**Comment by enea1982** [comment]
now I get this error what does it mean ?


 Traceback (most recent call last):
  File "/home/demian82/Desktop/AmazonOffers-TelegramBot-main/bot.py", line 4, in <module>
    from amazon_api import search_items
  File "/home/demian82/Desktop/AmazonOffers-TelegramBot-main/amazon_api.py", line 2, in <module>
    from paapi5_python_sdk.models.partner_type import PartnerType
ModuleNotFoundError: No module named 'paapi5_python_sdk.models'

**Comment by alefiori82** [comment]
You are using the sdk package not directly this wrapper. Follow the instructions to install and use my package correctly.

**Comment by enea1982** [comment]
come facio ad inserire il tuo pacheto nel progeto di samir ?
