### ISSUE TITLE
Take from whom the product is shipped

### ISSUE THREAD

**Issue by giuseppe99barchetta** [alefiori82/amazon-paapi5#5]
As object of issue I'm interested to take from whom the product is shipped.

Ex:

Sold by ABCDE shipped by **_BCDEF_**

Thanks!

**Comment by alefiori82** [comment]
All the information you can get with the library are the ones described in the [official guide of Amazon Products API](https://webservices.amazon.com/paapi5/documentation/).
In particular you can retrieve for each offer the [DeliveryInfo](https://webservices.amazon.com/paapi5/documentation/offers.html#deliveryinfo) which include IsAmazonFulfilled, IsFreeShippingEligible and IsPrimeEligible.
